Remove 50G upload limit on python client
flexcompute/Flow360 pull request #411
Opened 2024-08-05 18:15 UTC by benflexcompute

2024-08-08 19:36 UTC, lei-flex requested changes

2024-08-08 19:36 UTC, lei-flex commented on flow360/cloud/s3_utils.py
> +                Config=_get_dynamic_upload_config(float(os.path.getsize(file_name))),
why change to float?

2024-08-08 19:53 UTC, benflexcompute commented on flow360/cloud/s3_utils.py
> +                Config=_get_dynamic_upload_config(float(os.path.getsize(file_name))),
Removed float

2024-08-08 20:12 UTC, benflexcompute commented on flow360/cloud/s3_utils.py
> +        :param max_parts: Maximum number of parts allowed for multipart upload.
remove function and inline. Link doc reference

2024-08-09 14:27 UTC, lei-flex approved these changes
ship it

2024-08-09 14:40 UTC, merged